# FGDW002 - Fibaro Door Window Sensor 2
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/604
-   deviceName: FGDW002 - Fibaro Door Window Sensor 2
    manufacturerId: 271
    productTypeId: 1794
    groups:
        1: 1
        2: 1
        3: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
    #wakeup: 3600

-   deviceName: FGDW002 - Fibaro Door Window Sensor 1.5
    manufacturerId: 271
    productTypeId: 1793
    groups:
        1: 1
        2: 1
        3: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
    #wakeup: 3600

-   deviceName: FGDW002 - Fibaro Door Window Sensor 1
    manufacturerId: 271
    productTypeId: 1792
    groups:
        1: 1
        2: 1
        3: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
    #wakeup: 3600

# ZW100 Multisensor 6 1.12
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/778
-   deviceName: ZW100 Multisensor 6
    manufacturerId: 134
    productTypeId: 2
    groups:
        1: 1
    config: 
        3_2: 10
        5_1: 2
        101_4: 1

# FGWP102 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/513
-   deviceName: FGWP102 Metered Wall Plug Switch
    manufacturerId: 271
    productTypeId: 1538
    groups:
        1: 1
        2: 1
        3: 1

# FGWP101 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/130
-   deviceName: FGWP101 Metered Wall Plug Switch
    manufacturerId: 271
    productTypeId: 1536
    groups:
        1: 1
        2: 1
        3: 1

# FGBS001 Universal Binary Sensor
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/126
-   deviceName: FGBS001 Universal Binary Sensor
    manufacturerId: 271
    productTypeId: 1281
    groups:
        1: 1
        2: 1
        3: 1
        
# ZW139 Nano Switch Gen5 (without meter)
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/648
-   deviceName: ZW139 Nano Switch Gen5 (without meter)
    manufacturerId: 134
    productTypeId: 3
    groups:
        1: 1
        3: 1
    config: 
        120_1: 0
        121_1: 0

# TPS412 Touch Panel Switch 2 Channel
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/429
-   deviceName: TPS412 Touch Panel Switch 2 Channel
    manufacturerId: 351
    productTypeId: 16673
    groups:
        1: 1
        2: 1
        3: 1

-   deviceName: BeNext Panic Watch
    manufacturerId: 138
    productTypeId: 21
    groups:
        1: 1
    config:
        4_1: 0        