name: .NET Core

on: [push]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet publish -c Release --self-contained -r linux-arm -o ./publish /p:PublishTrimmed=true
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: publish/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
